-- =====================================================
-- Create Deduplication Metrics Table
-- =====================================================
-- This script creates a table to track deduplication performance,
-- language processing statistics, and race condition metrics
-- for the vector embedding deduplication system.
--
-- Run this script in your Supabase SQL Editor AFTER running
-- the vector embeddings schema script.
-- =====================================================

-- Step 1: Create the deduplication_metrics table
CREATE TABLE IF NOT EXISTS deduplication_metrics (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    family_id uuid NOT NULL,
    operation_type text NOT NULL CHECK (operation_type IN (
        'extract_context',
        'extract_regulation',
        'extract_coping',
        'regenerate_all_context',
        'regenerate_all_regulation',
        'backfill_embeddings'
    )),
    table_name text NOT NULL CHECK (table_name IN (
        'insight_bullet_points',
        'contextual_insights',
        'both'
    )),
    
    -- Core deduplication metrics
    candidates_generated integer NOT NULL DEFAULT 0,
    duplicates_found integer NOT NULL DEFAULT 0,
    insights_inserted integer NOT NULL DEFAULT 0,
    insights_fused integer NOT NULL DEFAULT 0,
    insights_rewritten integer NOT NULL DEFAULT 0,
    race_condition_duplicates integer NOT NULL DEFAULT 0,
    
    -- Language processing metrics
    languages_detected jsonb NOT NULL DEFAULT '{}', -- {"en": 10, "es": 2, "fr": 1}
    translations_performed integer NOT NULL DEFAULT 0,
    
    -- Performance metrics
    processing_time_ms integer NOT NULL DEFAULT 0,
    embedding_generation_time_ms integer NOT NULL DEFAULT 0,
    similarity_search_time_ms integer NOT NULL DEFAULT 0,
    
    -- Model and configuration tracking
    embedding_model text NOT NULL DEFAULT 'text-embedding-3-small',
    similarity_threshold_used float NOT NULL DEFAULT 0.85,
    
    -- Additional context
    batch_size integer,
    api_provider text, -- 'openai', 'anthropic', 'xai', 'google'
    
    created_at timestamp with time zone DEFAULT now()
);

-- Step 2: Add indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_deduplication_metrics_family_id 
ON deduplication_metrics (family_id);

CREATE INDEX IF NOT EXISTS idx_deduplication_metrics_operation_type 
ON deduplication_metrics (operation_type);

CREATE INDEX IF NOT EXISTS idx_deduplication_metrics_created_at 
ON deduplication_metrics (created_at);

CREATE INDEX IF NOT EXISTS idx_deduplication_metrics_family_operation 
ON deduplication_metrics (family_id, operation_type, created_at);

-- Step 3: Add RLS policies
ALTER TABLE deduplication_metrics ENABLE ROW LEVEL SECURITY;

-- Users can only see their own family's metrics
CREATE POLICY "users_can_view_own_family_metrics" ON deduplication_metrics
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM families 
            WHERE families.id = deduplication_metrics.family_id 
            AND families.user_id = auth.uid()
        )
    );

-- Only the service can insert metrics (from Edge Functions)
CREATE POLICY "service_role_can_insert_metrics" ON deduplication_metrics
    FOR INSERT WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

-- Step 4: Add table comments
COMMENT ON TABLE deduplication_metrics IS 
'Tracks performance and effectiveness metrics for the vector embedding deduplication system, including language processing statistics and race condition prevention.';

COMMENT ON COLUMN deduplication_metrics.candidates_generated IS 'Number of insight candidates generated by AI before deduplication';
COMMENT ON COLUMN deduplication_metrics.duplicates_found IS 'Number of duplicates detected through vector similarity';
COMMENT ON COLUMN deduplication_metrics.insights_inserted IS 'Number of new insights successfully inserted after deduplication';
COMMENT ON COLUMN deduplication_metrics.insights_fused IS 'Number of insights that were merged with existing similar content';
COMMENT ON COLUMN deduplication_metrics.insights_rewritten IS 'Number of insights that were rewritten to avoid similarity';
COMMENT ON COLUMN deduplication_metrics.race_condition_duplicates IS 'Number of duplicates caught by database constraints (safety net)';
COMMENT ON COLUMN deduplication_metrics.languages_detected IS 'JSON object with language codes as keys and occurrence counts as values';
COMMENT ON COLUMN deduplication_metrics.translations_performed IS 'Number of non-English texts translated before embedding generation';
COMMENT ON COLUMN deduplication_metrics.processing_time_ms IS 'Total processing time for the entire operation in milliseconds';
COMMENT ON COLUMN deduplication_metrics.embedding_generation_time_ms IS 'Time spent generating embeddings in milliseconds';
COMMENT ON COLUMN deduplication_metrics.similarity_search_time_ms IS 'Time spent on vector similarity searches in milliseconds';
COMMENT ON COLUMN deduplication_metrics.similarity_threshold_used IS 'The similarity threshold that was used for deduplication (0.0-1.0)';

-- Step 5: Create helper functions for metrics analysis

-- Function to get deduplication effectiveness for a family
CREATE OR REPLACE FUNCTION get_deduplication_effectiveness(
    target_family_id uuid,
    time_period_days integer DEFAULT 30
)
RETURNS TABLE (
    operation_type text,
    total_operations bigint,
    avg_candidates_per_operation numeric,
    avg_duplicates_found numeric,
    avg_duplicates_prevented_pct numeric,
    avg_race_conditions numeric,
    most_common_languages jsonb
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        dm.operation_type,
        COUNT(*) as total_operations,
        ROUND(AVG(dm.candidates_generated), 2) as avg_candidates_per_operation,
        ROUND(AVG(dm.duplicates_found), 2) as avg_duplicates_found,
        ROUND(
            CASE 
                WHEN AVG(dm.candidates_generated) > 0 THEN
                    (AVG(dm.duplicates_found) / AVG(dm.candidates_generated)) * 100
                ELSE 0 
            END, 2
        ) as avg_duplicates_prevented_pct,
        ROUND(AVG(dm.race_condition_duplicates), 2) as avg_race_conditions,
        jsonb_object_agg(
            lang_key, 
            lang_count ORDER BY lang_count DESC
        ) FILTER (WHERE lang_key IS NOT NULL) as most_common_languages
    FROM deduplication_metrics dm,
         LATERAL jsonb_each_text(dm.languages_detected) AS lang(lang_key, lang_count)
    WHERE 
        dm.family_id = target_family_id
        AND dm.created_at >= NOW() - INTERVAL '%s days' % time_period_days
    GROUP BY dm.operation_type
    ORDER BY total_operations DESC;
END;
$$ LANGUAGE plpgsql;

-- Function to get language processing statistics
CREATE OR REPLACE FUNCTION get_language_processing_stats(
    target_family_id uuid DEFAULT NULL,
    time_period_days integer DEFAULT 30
)
RETURNS TABLE (
    language_code text,
    total_occurrences bigint,
    operations_with_language bigint,
    avg_translations_per_operation numeric,
    total_translations bigint
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        lang.lang_key as language_code,
        SUM(lang.lang_count::bigint) as total_occurrences,
        COUNT(DISTINCT dm.id) as operations_with_language,
        ROUND(AVG(dm.translations_performed), 2) as avg_translations_per_operation,
        SUM(dm.translations_performed) as total_translations
    FROM deduplication_metrics dm,
         LATERAL jsonb_each_text(dm.languages_detected) AS lang(lang_key, lang_count)
    WHERE 
        (target_family_id IS NULL OR dm.family_id = target_family_id)
        AND dm.created_at >= NOW() - INTERVAL '%s days' % time_period_days
        AND lang.lang_key IS NOT NULL
    GROUP BY lang.lang_key
    ORDER BY total_occurrences DESC;
END;
$$ LANGUAGE plpgsql;

-- Function to get performance metrics summary
CREATE OR REPLACE FUNCTION get_performance_summary(
    target_family_id uuid DEFAULT NULL,
    time_period_days integer DEFAULT 7
)
RETURNS TABLE (
    operation_type text,
    avg_total_time_ms numeric,
    avg_embedding_time_ms numeric,
    avg_similarity_search_time_ms numeric,
    avg_insights_per_second numeric,
    total_operations bigint
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        dm.operation_type,
        ROUND(AVG(dm.processing_time_ms), 2) as avg_total_time_ms,
        ROUND(AVG(dm.embedding_generation_time_ms), 2) as avg_embedding_time_ms,
        ROUND(AVG(dm.similarity_search_time_ms), 2) as avg_similarity_search_time_ms,
        ROUND(
            CASE 
                WHEN AVG(dm.processing_time_ms) > 0 THEN
                    (AVG(dm.insights_inserted) * 1000.0) / AVG(dm.processing_time_ms)
                ELSE 0 
            END, 3
        ) as avg_insights_per_second,
        COUNT(*) as total_operations
    FROM deduplication_metrics dm
    WHERE 
        (target_family_id IS NULL OR dm.family_id = target_family_id)
        AND dm.created_at >= NOW() - INTERVAL '%s days' % time_period_days
    GROUP BY dm.operation_type
    ORDER BY total_operations DESC;
END;
$$ LANGUAGE plpgsql;

-- Step 6: Create a view for easy monitoring
CREATE OR REPLACE VIEW deduplication_metrics_summary AS
SELECT 
    dm.family_id,
    dm.operation_type,
    dm.table_name,
    COUNT(*) as total_operations,
    SUM(dm.candidates_generated) as total_candidates,
    SUM(dm.duplicates_found) as total_duplicates_found,
    SUM(dm.insights_inserted) as total_insights_inserted,
    SUM(dm.race_condition_duplicates) as total_race_conditions,
    SUM(dm.translations_performed) as total_translations,
    ROUND(AVG(dm.processing_time_ms), 2) as avg_processing_time_ms,
    MAX(dm.created_at) as last_operation_at,
    ROUND(
        CASE 
            WHEN SUM(dm.candidates_generated) > 0 THEN
                (SUM(dm.duplicates_found)::numeric / SUM(dm.candidates_generated)) * 100
            ELSE 0 
        END, 2
    ) as duplicate_detection_rate_pct
FROM deduplication_metrics dm
WHERE dm.created_at >= NOW() - INTERVAL '30 days'
GROUP BY dm.family_id, dm.operation_type, dm.table_name
ORDER BY total_operations DESC;

-- Add comment to the view
COMMENT ON VIEW deduplication_metrics_summary IS 
'Summary view of deduplication metrics for the last 30 days, grouped by family, operation type, and table.';

-- Step 7: Create cleanup function for old metrics
CREATE OR REPLACE FUNCTION cleanup_old_deduplication_metrics(
    days_to_keep integer DEFAULT 90
)
RETURNS integer AS $$
DECLARE
    deleted_count integer;
BEGIN
    DELETE FROM deduplication_metrics 
    WHERE created_at < NOW() - INTERVAL '%s days' % days_to_keep;
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    
    RAISE NOTICE 'Deleted % old deduplication metrics records', deleted_count;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Step 8: Verify table creation
SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'deduplication_metrics'
ORDER BY ordinal_position;

-- Show indexes
SELECT 
    indexname,
    indexdef
FROM pg_indexes
WHERE tablename = 'deduplication_metrics'
ORDER BY indexname;

-- =====================================================
-- USAGE EXAMPLES
-- =====================================================
--
-- Insert a metrics record (typically done by Edge Function):
-- INSERT INTO deduplication_metrics (
--     family_id, operation_type, table_name, candidates_generated,
--     duplicates_found, insights_inserted, languages_detected,
--     translations_performed, processing_time_ms
-- ) VALUES (
--     'family-uuid-here', 'extract_context', 'contextual_insights', 15,
--     3, 12, '{"en": 10, "es": 3, "fr": 2}',
--     5, 2500
-- );
--
-- Get effectiveness for a family:
-- SELECT * FROM get_deduplication_effectiveness('family-uuid-here', 30);
--
-- Get language stats:
-- SELECT * FROM get_language_processing_stats('family-uuid-here', 30);
--
-- Get performance summary:
-- SELECT * FROM get_performance_summary('family-uuid-here', 7);
--
-- View summary:
-- SELECT * FROM deduplication_metrics_summary WHERE family_id = 'family-uuid-here';
--
-- Cleanup old records:
-- SELECT cleanup_old_deduplication_metrics(90);
-- =====================================================